
// Game Physics and Stats Configuration

export const STAT_DECAY_RATE = {
  HUNGER: 0.08, 
  THIRST: 0.12,
  STAMINA_REGEN: 15,
  STAMINA_DRAIN_SPRINT: 25,
  HEALTH_REGEN_PASSIVE: 1,
};

export const PHYSICS = {
  GRAVITY: -35,
  JUMP_FORCE: 14,
  MOVE_SPEED: 8,
  SPRINT_SPEED: 16,
  CROUCH_SPEED: 4,
  SLIDE_SPEED: 22, 
  SLIDE_FRICTION: 1.5, 
  GROUND_FRICTION: 10,
  AIR_FRICTION: 1,
  ACCELERATION: 15,
  AIR_ACCELERATION: 3,
  MAX_JUMPS: 2,
  PLAYER_RADIUS: 0.5,
  PLAYER_HEIGHT_STANDING: 1.8,
  PLAYER_HEIGHT_CROUCH: 1.0,
  PLAYER_HEIGHT_SLIDE: 0.8,
};

export const WORLD_SIZE = 400; // Expanded world
export const CONTAINER_LIFETIME = 5 * 60 * 1000;
export const INVENTORY_SIZE = 32;
